version: "3.7"

services:
  db:
    hostname: mediasteam_mysql
    container_name: mediasteam_mysql
    image: mysql:5.7
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db_ms
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=app_ms
      - MYSQL_PASSWORD=1234
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - TZ:Asia/Seoul

  redis:
    container_name: mediasteam_radis
    hostname: mediasteam_radis
    image: redis:alpine
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"

  backend:
    container_name: mediasteam_backend
    hostname: mediasteam_backend
    restart: always
    build:
      context: ../../mediaSteam
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - db
      - redis

networks:
  default:
    name: mediasteam_network
