spring:
  config:
    activate:
      on-profile: oauth

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 51f2d2ac054e0496a65943501c480612
            client-secret: S84XsL7SqyY51y4S2X8KX8gfsaSoHDJt
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
app:
  auth:
    tokenSecret: 0D8FA4B1461274DFAA27E2EBC702CBD2DB6EBFD7A6C74A7D083B6A88F0F296F4
    tokenExpirationMsec: 86400000 # 1Day
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect