spring:
  config:
    activate:
      on-profile: localdb

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mediasteam_mysql:3306/db_ms?characterEncoding=UTF-8
    username: app_ms
    password: 1234

  flyway:
    baseline-description: false
    baseline-version: 1
